---
- name: Debian tasks
  become: true
  environment:
    HTTP_PROXY: "{{ r_docker_repos[facts_distro_lower][facts_distro_major]['use_proxy']|default(False)  | ternary(proxy.http|default(''), '', '') }}"
    HTTPS_PROXY: "{{ r_docker_repos[facts_distro_lower][facts_distro_major]['use_proxy']|default(False) | ternary(proxy.https|default(''), '', '') }}" 
  block:
    - name: Check Repo definition
      ansible.builtin.assert:
        that:
          - r_docker_repos[facts_distro_lower][facts_distro_major] is defined
    - name: Add Docker repo
      when:
        - r_docker_add_repo
        - not (r_docker_repos[facts_distro_lower][facts_distro_major]['disabled']|default(False))
      block:
        - name: Add Docker GPG key (debian < 11)
          apt_key: 
            url: "{{ r_docker_repos[facts_distro_lower][facts_distro_major]['gpg'] }}"
            state: present
          when:
            - "'gpg' in r_docker_repos[facts_distro_lower][facts_distro_major]"
            - facts_distro_major|int < 11
        - name: Download Docker GPG key (debian >= 11)
          ansible.builtin.get_url:
            url: "{{ r_docker_repos[facts_distro_lower][facts_distro_major]['gpg'] }}"
            dest: /usr/share/keyrings/docker-archive-keyring.gpg
          when:
            - "'gpg' in r_docker_repos[facts_distro_lower][facts_distro_major]"
            - facts_distro_major|int >= 11
        - name: Add Docker GPG key (debian >= 11)
          ansible.builtin.shell:
            cmd: gpg --dearmor /usr/share/keyrings/docker-archive-keyring.gpg
          when:
            - "'gpg' in r_docker_repos[facts_distro_lower][facts_distro_major]"
            - facts_distro_major|int >= 11
        - name: Add Debian repository
          apt_repository:
            repo: deb {{ r_docker_repos[facts_distro_lower][facts_distro_major]['url'] }}
            update_cache: yes
            filename: docker-ce-stable
            state: present
    - name: Remove Docker repo
      when: (not r_docker_add_repo) or (r_docker_repos[facts_distro_lower][facts_distro_major]['disabled']|default(False))
      file:
        path: /etc/apt/sources.list.d/docker-ce-stable.list
        state: absent
