---
- name: OS prerequisite for "{{ facts_os_info }}"
  include_tasks: "{{ facts_distro_lower }}.yml"
  tags: always
- import_tasks: install.yml
  tags: 
    - r_docker_install
- import_tasks: remove.yml
  tags:
    - never
    - ROLE_DOCKER_REMOVE